from _typeshed import StrOrBytesPath
from collections.abc import Buffer

from typing_extensions import CapsuleType

def init_magic(db_path: StrOrBytesPath, /) -> CapsuleType: ...
def describe_file(magic: CapsuleType, path: StrOrBytesPath, is_mime: bool, /) -> str: ...
def describe_bytes(magic: CapsuleType, data: Buffer, is_mime: bool, /) -> str: ...
def libmagic_version() -> int: ...
